import { OptionItem, CategoryKey, ModelConfig } from './types';

export const MODELS: ModelConfig[] = [
  { id: 'common', name: '공통 (Universal)', description: '모든 모델에 안정적인 범용 구조' },
  { id: 'sora', name: 'Sora', description: '서술형, 긴 문맥, 감정 표현 중심' },
  { id: 'runway', name: 'Runway Gen-3', description: '명확한 섹션 구분, 짧고 구체적인 지시' },
  { id: 'kling', name: 'Kling AI', description: '객관적 요소(위치, 각도) 중시, 리스트형' },
  { id: 'veo', name: 'Veo', description: '시네마틱, 조명 세부 묘사, 고화질' },
  { id: 'pika', name: 'Pika', description: '짧고 간결, 핵심 요소 위주' },
];

export const OPTIONS: Record<CategoryKey, OptionItem[]> = {
  shotType: [
    { value: 'Extreme close-up (ECU)', label: '극클로즈업 (아주 가까운 얼굴/사물)' },
    { value: 'Close-up (CU)', label: '클로즈업 (얼굴·손 등 가까이 촬영)' },
    { value: 'Medium close-up (MCU)', label: '상반신 중심 샷' },
    { value: 'Medium shot (MS)', label: '전신 일부까지 보이는 기본 샷' },
    { value: 'Medium wide shot (MWS)', label: '인물 + 주변 배경이 살짝 보이는 중간 와이드' },
    { value: 'Wide shot (WS)', label: '전체 장면이 보이는 와이드 샷' },
    { value: 'Extreme wide shot (EWS)', label: '풍경·공간 중심 초광각 샷' },
    { value: 'Over-the-shoulder shot (OTS)', label: '어깨 너머 샷 (대화/관찰)' },
    { value: 'Point-of-view shot (POV)', label: '인물 시점 샷' },
    { value: 'Low-angle / high-angle shot', label: '하이/로우 앵글 (위/아래)' },
  ],
  cameraMovement: [
    { value: 'Slow dolly-in', label: '천천히 앞으로 당기는 카메라' },
    { value: 'Slow dolly-out', label: '천천히 뒤로 빠지는 카메라' },
    { value: 'Smooth pan left', label: '왼쪽으로 부드럽게 이동' },
    { value: 'Smooth pan right', label: '오른쪽으로 부드럽게 이동' },
    { value: 'Tilt up', label: '위로 틸트' },
    { value: 'Tilt down', label: '아래로 틸트' },
    { value: 'Static locked camera', label: '고정된 카메라 (움직임 없음)' },
    { value: 'Gentle handheld motion', label: '약간 흔들리는 핸드헬드 느낌' },
    { value: 'Slow orbit', label: '대상을 천천히 빙글 돌며 촬영' },
    { value: 'Tracking shot', label: '대상의 움직임을 따라가는 촬영' },
  ],
  framing: [
    { value: 'Rule-of-thirds framing', label: '삼등분 구도' },
    { value: 'Centered composition', label: '중앙 배치 구도' },
    { value: 'Symmetrical framing', label: '좌우 대칭 구도' },
    { value: 'Leading lines', label: '시선 유도선 사용' },
    { value: 'Deep-focus composition', label: '깊은 심도 (전체 선명)' },
    { value: 'Shallow depth of field', label: '얕은 심도 (배경 흐림)' },
    { value: 'Layered composition', label: '전경-중경-배경 층구조' },
    { value: 'Wide negative space', label: '여백이 넓은 구도' },
    { value: 'Foreground framing', label: '전경 오브젝트 활용' },
    { value: 'Triangular arrangement', label: '삼각형 배치 구도' },
  ],
  action: [
    { value: 'Speaking or presenting', label: '발표/말하는 장면' },
    { value: 'Writing/drawing on board', label: '칠판/보드에 쓰기' },
    { value: 'Walking into frame', label: '화면 안으로 걸어 들어오기' },
    { value: 'Turning toward camera', label: '카메라를 향해 돌아보기' },
    { value: 'Discussing at desk', label: '책상에서 토론하기' },
    { value: 'Pointing at object', label: '무언가를 가리키기' },
    { value: 'Showing surprise/curiosity', label: '놀람·호기심 표현' },
    { value: 'Hand gestures while explaining', label: '설명하며 손짓' },
    { value: 'Observing closely', label: '자세히 들여다보기' },
    { value: 'Interacting with another person', label: '다른 인물과 상호작용' },
  ],
  characters: [
    { value: 'Single student', label: '학생 1명' },
    { value: 'Two students discussing', label: '두 학생 토론 장면' },
    { value: 'Small group (3–4 students)', label: '소그룹 학생 3–4명' },
    { value: 'Teacher explaining', label: '선생님 설명 장면' },
    { value: 'Child observing', label: '어린이가 관찰하는 장면' },
    { value: 'Mixed children group', label: '다양한 아이들 구성' },
    { value: 'Adult professional', label: '성인 전문가' },
    { value: 'Parent–child pair', label: '부모+아이 구성' },
    { value: 'Neutral expressions', label: '중립적 표정' },
    { value: 'Expressive emotions', label: '감정 표현 뚜렷' },
  ],
  environment: [
    { value: 'Modern classroom', label: '현대적인 교실 배경' },
    { value: 'Traditional classroom', label: '일반 교실 (칠판·책상)' },
    { value: 'School hallway', label: '학교 복도' },
    { value: 'Science lab', label: '과학실험실' },
    { value: 'Library interior', label: '도서관/열람실' },
    { value: 'Outdoor playground', label: '야외 놀이터' },
    { value: 'Park / nature scene', label: '공원·자연 배경' },
    { value: 'Clean studio background', label: '심플 스튜디오 배경' },
    { value: 'Home interior', label: '집 내부 (따뜻한 조명)' },
    { value: 'Minimal white background', label: '미니멀 흰 배경' },
  ],
  lighting: [
    { value: 'Soft natural daylight', label: '부드러운 자연광' },
    { value: 'Warm indoor lighting', label: '따뜻한 실내 조명' },
    { value: 'Cool-toned lighting', label: '차가운 색감의 조명' },
    { value: 'Rim/back light', label: '역광·테두리광' },
    { value: 'Diffused soft light', label: '확산 소프트 조명' },
    { value: 'High-key lighting', label: '밝고 선명한 조명' },
    { value: 'Low-key dramatic light', label: '어두워 드라마틱한 조명' },
    { value: 'Sunset warm glow', label: '해질녘 따뜻한 빛' },
    { value: 'Overhead classroom light', label: '교실 천장등 조명' },
    { value: 'Neutral balanced light', label: '중성 균형 조명' },
  ],
  colorPalette: [
    { value: 'Pastel tones', label: '파스텔 톤' },
    { value: 'Bright vivid colors', label: '밝고 선명한 컬러' },
    { value: 'Earthy natural palette', label: '자연·흙색 계열 톤' },
    { value: 'Warm yellow-orange tones', label: '따뜻한 노랑/주황 계열' },
    { value: 'Cool blue-green tones', label: '차가운 파랑/초록 계열' },
    { value: 'High-contrast palette', label: '대비 강한 컬러' },
    { value: 'Muted desaturated tones', label: '채도 낮은 톤' },
    { value: 'Korean textbook palette', label: '교과서 스타일 컬러' },
    { value: 'White-dominant palette', label: '화이트 기반 톤' },
    { value: 'Retro warm palette', label: '레트로 따뜻한 필터 톤' },
  ],
  style: [
    { value: 'Korean textbook illustration', label: '교과서 일러스트 스타일' },
    { value: 'Semi-realistic digital art', label: '반사실적 디지털 스타일' },
    { value: 'Soft watercolor look', label: '부드러운 수채화풍' },
    { value: '2D flat animation style', label: '2D 플랫 애니메이션' },
    { value: '3D cinematic style', label: '3D 시네마틱 룩' },
    { value: 'Minimal modern design', label: '미니멀 모던' },
    { value: 'Storybook illustration', label: '동화책 스타일' },
    { value: 'Anime-inspired shading', label: '애니메이션풍 음영' },
    { value: 'Hyper-realistic detail', label: '사실적 디테일' },
    { value: 'Cutout graphic style', label: '컷아웃 그래픽 스타일' },
  ],
  negatives: [
    { value: 'Avoid face distortion', label: '얼굴 왜곡 금지' },
    { value: 'Avoid unnatural hands', label: '손가락/손 모양 이상 금지' },
    { value: 'Avoid shaky camera', label: '카메라 흔들림 금지' },
    { value: 'Avoid excessive motion blur', label: '과도한 모션블러 금지' },
    { value: 'Avoid crowded backgrounds', label: '복잡한 배경 금지' },
    { value: 'Avoid oversaturated colors', label: '과채도 색감 금지' },
    { value: 'Avoid inconsistent characters', label: '인물 스타일 변화 금지' },
    { value: 'Avoid unrealistic proportions', label: '비현실 비율 금지' },
    { value: 'Avoid random object placement', label: '불규칙 오브젝트 금지' },
    { value: 'Avoid extreme lighting', label: '극단적 조명 금지' },
  ]
};

// Additional hardcoded helper for "Scene" and "Duration" which aren't dropdowns
export const DEFAULTS = {
    duration: '5',
    fps: '24',
    ratio: '16:9'
};
